name: Pulumi
on:
  pull_request:
    paths-ignore:
      - infra/**
      - .github/workflows/pull_request_infra.yml
jobs:
  preview:
    name: Pulumi Preview
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "osakunta"
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: prod
          cloud-url: ${{ secrets.PULUMI_CLOUD_URL }}
